### PR TITLE
initial cmake-based build setup for Omega

### PR DESCRIPTION
**Pull request by grnydawn**
The PR includes the initial cmake-based build-setup for Omega

It supports two modes of Omega builds:
1. Standalone
2. E3SM Omega component

It includes miniWeather YAKL version to test the setup(tested on Frontier of ORNL).

The main purpose of this PR is to initiate discussions on Omega build design and implementation.

### CODE REVIEW

**Comment by grnydawn** [comment]
To build/run Omega standalone(on Frontier of ORNL):

`#!/bin/bash

ACCOUNT=<account>
E3SM_HOME="<path to OMEGA>"

source ${MODULESHOME}/init/bash
# on Frontier
module load PrgEnv-amd cray-parallel-netcdf cmake craype-accel-amd-gfx90a

COMP_HOME=${E3SM_HOME}/components
OUTROOT="<path to output directory>"

# rm -rf ${OUTROOT}
mkdir -p ${OUTROOT}

cd "${OUTROOT}"

cmake \
  -DOMEGA_BUILD_EXECUTABLE=ON \
  -DOMEGA_BUILD_TEST=ON \
  -DOMEGA_INSTALL_PREFIX="${OUTROOT}/install" \
  -DCMAKE_CXX_COMPILER=CC \
  -DOMEGA_ARCH="HIP" \
  -DOMEGA_HIP_FLAGS="-DHAVE_MPI -DNO_INFORM -DGPU_AWARE_MPI -O3 -ffast-math -D__HIP_ROCclr__ -D__HIP_ARCH_GFX90A__=1 --rocm-path=${ROCM_PATH} --offload-arch=gfx90a -x hip -I${PNETCDF_DIR}/include" \
  -DCMAKE_EXE_LINKER_FLAGS="--rocm-path=${ROCM_PATH} -L${ROCM_PATH}/lib -lamdhip64"   \
  -DOMEGA_LDFLAGS="-L${PNETCDF_DIR}/lib -lpnetcdf"  \
  ${COMP_HOME}/omega

# to run Omega
cd "${OUTROOT}"
make
cd src
./omega.exe
`

**Comment by grnydawn** [comment]
To build/run E3SM Omega component(on Frontier of ORNL):

Before running the cmake command, ${E3SM_ROOT}/components/CMakeLists.txt should be updated like below. This work-around is temporary until Omega build is linked properly to E3SM build.
```
...
# Include function definitions
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/cmake_util.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/build_mpas_model.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/build_omega.cmake) # <= added
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/build_eamxx.cmake)
include(${CMAKE_CURRENT_SOURCE_DIR}/cmake/build_model.cmake)
...
set(BUILDCONF ${CASEROOT}/Buildconf)

build_mpas_models()
build_omega() # <= added
...
```

And, "${E3SM_ROOT}/components/cmake/build_omega.cmake" should be created with the "build_omega" function that includes omega subdirectory.

```
function(build_omega)

  # set CIME source path relative to components
  set(CIMESRC_PATH "../cime/src")

  add_subdirectory("omega")

endfunction(build_omega)
```

Once, the above setup is in place, we can run the cmake command to build Omega within E3SM build system:

```
E3SM_HOME="<path to E3SM root directory>"
OUTROOT="<path to output directory>"
RES="T62_oQU120_ais20"
COMPSET="MPAS_LISIO_TEST"
CASEDIR="${OUTROOT}/${RES}.${COMPSET}"
ACCOUNT="<account>"
MACH=frontier

${E3SM_HOME}/cime/scripts/create_newcase --case "${CASEDIR}" --res ${RES} --compset ${COMPSET}  --machine ${MACH} --project ${ACCOUNT} --output-root "${OUTROOT}"

cd "${CASEDIR}"

./case.setup

./case.build
```

**Comment by amametjanov** [comment]
I added a PR to bring latest the E3SM `master` into Omega `develop`. If PR #18 is okay, we can rebase this branch onto the new `develop`.

**Comment by grnydawn** [comment]
@philipwjones, thanks for the suggestions. Please see below for the changes that I made per your suggestions.

* For the CIME changes and YAKL submodule, I think we need to sync the OMEGA repo so it's up to date with E3SM. Are the frontier changes on E3SM master now or do we need to wait and sync after those are merged?
=> Thanks to Az's recent merge, I was able to sync my branch with the recent E3SM version.

* Can you please remove the logger and spdlog. This will need a separate PR and discussion
=> I removed the logger and spdlog from the commit. In fact, I created a new branch that incorporates your suggestions (https://github.com/grnydawn/Omega/tree/ykim/omega/cmakebuild)

Can you replace the miniWeather code with simple dummy routines (eg. ocndummy.h, ocndummy.cpp, similar in infrastructure dirs) that have, say, just an output to std::out. I know using miniWeather was useful for testing YAKL, but it's going to create some conflicts later and we don't need all the extra miniweather env vars in the build. Similarly in the test dir.
=> I replaced the miniWeather code with a simple YAKL dummy routines so that it does not need a complex compiler flags for HIP but still works for YAKL testing. Please see the new branch for details(https://github.com/grnydawn/Omega/tree/ykim/omega/cmakebuild)

* For the standalone build, there seem to be a lot of flags (eg HIP flags) that should only be needed by YAKL? And I think we eventually want to supply a machine argument and grab these flags from the E3SM machine config even for standalone builds. If this is just a short-term solution while you figure out how to extract those from E3SM xml files, that's fine for now.
=> Yes, eventually, I will try to grab the compiler flgas from E3SM machine and compiler configurations.

Finally, we'll need documentation for the user and develop guides in the doc directory for this before we can approve.
=> I will add documentation for the user and develop guides, and once I have the initial documentation, I will create a new PR for this task.

I will leave this PR open for discussion until I create a new PR that eventually replace this PR.

**Comment by philipwjones** [comment]
Thanks @grnydawn  I'll approve the new PR when you replace this one.

**Comment by xylar** [comment]
@grnydawn, the replacement PR will also be useful for finding out how our linting tools are doing.  They're unhappy hear.  We'll need to see how they do on the new PR.

**Pull request closed without merging**
