### PR TITLE
Initial SUM, MIN and MAX reductions

### PR DESCRIPTION
**Pull request by amametjanov**
Initial SUM, MIN and MAX reductions.

Checklist
* [ x ] Testing
  * [ x ] A comment in the PR documents testing used to verify the changes including any tests that are added/modified/impacted.
  * [ x ] CTest unit tests for new features have been added per the approved design. 
  * [ x ] Unit tests have passed. Please provide a relevant CDash build entry for verification.

### CODE REVIEW

**Comment by amametjanov** [comment]
Testing.

**Comment by amametjanov** [comment]
This PR is ready for review.
Testing on Frontier:
```
$ cd components/omega/
$ module load cmake/3.23.2
$ rm -rf build && mkdir build && cd build
$ export PARMETIS_ROOT=/ccs/proj/cli115/software/polaris/frontier/spack/dev_polaris_0_3_0_crayclanggpu_mpich/var/spack/environments/dev_polaris_0_3_0_crayclanggpu_mpich/.spack-env/view
$ cmake \
   -DOMEGA_CIME_COMPILER=crayclanggpu \
   -DOMEGA_CIME_MACHINE=frontier \
   -DOMEGA_PARMETIS_ROOT=${PARMETIS_ROOT}\
   -DOMEGA_BUILD_TEST=ON \
   -Wno-dev \
   -S .. -B .
$ ln -isf /lustre/orion/cli115/world-shared/e3sm/inputdata/ocn/mpas-o/oQU240/ocean.QU.240km.151209.nc test/OmegaMesh.nc
$ ln -isf /lustre/orion/cli115/world-shared/e3sm/inputdata/ocn/mpas-o/oQU240/omega/initial_state.230220.nc test/OmegaSphereMesh.nc
$ ln -isf /lustre/orion/cli115/world-shared/e3sm/inputdata/ocn/mpas-o/oQU240/omega/PlanarPeriodic48x48.nc test/OmegaPlanarMesh.nc
$ ./omega_build.sh
$ salloc -A cli115 -t 00:30:00 -p batch -N 1 -q debug
$ ./omega_ctest.sh
...
      Start 15: REDUCTIONS_TEST
15/16 Test #15: REDUCTIONS_TEST ..................   Passed    0.61 sec
...
100% tests passed, 0 tests failed out of 16
```

**Review by philipwjones — CHANGES_REQUESTED** [review]
This looks good @amametjanov  both from a code inspection and repeating the unit test. I may add some additional tests later that really stress the ddsum algorithm, but the current version is good enough. Only one request - can you please add documentation? The user guide just needs a brief description with a pointer to the developer guide since there are no user-configurable options. The developer guide should give some examples of the available functionality. Thanks.

**Comment by philipwjones** [comment]
@amametjanov  - one other thing I forgot, @grnydawn has modified the Ctest framework to check for a non-zero return code from main in every unit test in addition to any FAILs. You can see the changes needed in #93 but you basically need to modify your unit test driver to accumulate any errors into a return code and add a return at the end of main. Thanks.

**Comment by amametjanov** [comment]
Thank you. I pushed documentation and CTest updates.

**Review by philipwjones — APPROVED** [review]
Thanks for adding the docs @amametjanov  This looks good to go. @mark-petersen had mentioned a min-max-sum function, but I think that should go somewhere else, so I will go ahead and merge this after doing some quick retesting.

**Pull request merged**
