### PR TITLE
Refactor: Migrate Omega from YAKL to Kokkos

### PR DESCRIPTION
**Pull request by grnydawn**
This PR aims to gather reviews on refactoring Omega to work with Kokkos.

All YAKL codes in the original Omega, including the unit tests, have been migrated to Kokkos to demonstrate the migration approaches.

Building Omega using CMake should remain unchanged, although several new optional macros have been added.

As of now, no documentation has been created for this migration. Please refer to the code where YAKL was previously used.

All unit tests, with one exception, have passed on Frontier, Perlmutter, and Chrysalis.

**** Commit message ****

- The Omega build system builds and links with Kokkos.
- Several Kokkos functions are wrapped in the Omega namespace.
- Previous YAKL codes in Omega modules have been translated to Kokkos.
- All unit tests have also been translated to Kokkos.
- The translation has been tested on Frontier GPU (HIP)/CPU (OpenMP), on Perlmutter GPU (CUDA)/CPU (OpenMP), and on Chrysalis CPU (OpenMP).
- On CPUs, the default parallelization is set to OpenMP.

### CODE REVIEW

**Review by philipwjones — CHANGES_REQUESTED** [review]
@grnydawn  This generally looks good and nice to do it all in one big chunk. A few things though:

It looks like you've picked up a lot of changes in externals. Was this because our repo hasn't been synced in a while? If so, I can take care of that (might just do it anyway) and then we can rebase so these mods don't show up.

We'll also need to a final linting pass to fix the CI errors.

There are cases here and there where the old YAKL code is commented out and should just be removed.

I did verify testing on Chrysalis and Frontier. Although everything passes, some of the tests (esp on Chrysalis) were running substantially (10x) slower. It's not a show-stopper and we can track it down after merging and fix later.

I get warnings on Chrysalis about OMP_PROC_BIND not being set, so we might want to grab the threading environment variables from the E3SM machine files and add to your scripts.

**Comment by grnydawn** [comment]
@philipwjones , Thanks for the comments.

It looks like you've picked up a lot of changes in externals. Was this because our repo hasn't been synced in a while? If so, I can take care of that (might just do it anyway) and then we can rebase so these mods don't show up.
=> I think you're right. I did not intend to particularly include the changes in the externals. I think that we may just need to sync with E3SM as you pointed out. 

We should also follow the branch naming convention for the final PR
=> I was not aware of the branch naming convention. I will try to follow it.

We'll also need to a final linting pass to fix the CI errors.
=> Yes, I have already fixed the CI error in my working branch.

There are cases here and there where the old YAKL code is commented out and should just be removed.
=> I have retained the YAKL code to facilitate comparison between the YAKL and Kokkos versions, allowing the code's owners to easily discern the differences. These will be removed in the final pull request (PR).

I did verify testing on Chrysalis and Frontier. Although everything passes, some of the tests (esp on Chrysalis) were running substantially (10x) slower. It's not a show-stopper and we can track it down after merging and fix later.
=> I also experience the slowdown on Chrysalis. In fact, it is even slower on Perlmutter than Chrysalis. Yes, we need to track it down sooner or later.

I get warnings on Chrysalis about OMP_PROC_BIND not being set, so we might want to grab the threading environment variables from the E3SM machine files and add to your scripts.
=> I will try to mute the warning in the final PR.

**Comment by philipwjones** [comment]
@grnydawn I just created a PR to sync with E3SM/master and get updated externals. After that's merged, you'll need to rebase this PR branch to get a clean PR. And probably test again to make sure Kokkos updates don't impact this.

**Comment by mwarusz** [comment]
> I did verify testing on Chrysalis and Frontier. Although everything passes, some of the tests (esp on Chrysalis) were running substantially (10x) slower. It's not a show-stopper and we can track it down after merging and fix later.

I just started looking at this PR, and so far I found out that this is because the default cpu parallelization is now OpenMP, and everything gets compiled with OpenMP enabled. Setting `OMP_NUM_THREADS=1` made the tests fast again on Chrysalis.

**Comment by grnydawn** [comment]
Accidentally, I closed this PR while working on rebasing my branch on Phil's recent PR. As I am about to create a new, final PR, I think it best to leave this PR closed. Instead, please review this branch: https://github.com/grnydawn/Omega/commits/ykim/omega/kokkosbuild-prfix/. Apologies for any inconvenience.

**Pull request closed without merging**
