### PR TITLE
[gh-pages] Remove old develop directory

### PR DESCRIPTION
**Pull request by xylar**
We need to remove the old `develop` directory on the `gh-pages` branch following the fix in #114

### CODE REVIEW

**Comment by xylar** [comment]
We should also update the link in the upper right-hand corner of https://github.com/E3SM-Project/Omega to https://docs.e3sm.org/Omega/omega

**Comment by xylar** [comment]
Eventually, https://docs.e3sm.org/Omega will be the full E3SM documentation, which will have a link to the Omega docs.  @altheaden is working on that in E3SM-Project/E3SM.

**Comment by xylar** [comment]
@philipwjones, another couple of things for you to take a look at when you have time.

**Review by philipwjones — APPROVED** [review]
Looks fine. I also made the change to the github site to point to the new location

**Comment by xylar** [comment]
Thanks, @philipwjones!

**Pull request merged**
