### PR TITLE
Add design document for Omega timers

### PR DESCRIPTION
**Pull request by philipwjones**
A draft design document for an initial timer implementation

Checklist
* [x] Documentation:
  * [x] Design document has been generated and added to the docs
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected

### CODE REVIEW

**Comment by philipwjones** [comment]
@sarats I know you had something more robust/extensive planned, so this can either be a placeholder or if you want to edit this doc to reflect your plans, that's fine too.

**Review by grnydawn — APPROVED** [review]
@philipwjones , @sarats, the timer design document looks good to me. If possible, I would like to add one more desired feature: generating a raw timing file in any machine readable format so that we can easily analyze timing output using external scripts or tools.

**Review by sarats — APPROVED** [review]
Thanks @philipwjones for taking the initiative and getting this done. This covers the minimum required functionality quite well. Areas such as device (GPU) support, threads etc. will evolve during implementation. 

Presently working on prototype development using [Caliper](https://software.llnl.gov/Caliper/index.html) and/or [PerfStubs](https://github.com/UO-OACISS/perfstubs) for external tool support.

**Comment by sarats** [comment]
> @philipwjones , @sarats, the timer design document looks good to me. If possible, I would like to add one more desired feature: generating a raw timing file in any machine readable format so that we can easily analyze timing output using external scripts or tools.

I'm looking into [Hatchet](https://hatchet.readthedocs.io/en/latest/data_generation.html) as an output format for facilitating easier parsing and performance comparisons.

**Comment by philipwjones** [comment]
Thanks @sarats @grnydawn . A question for you guys though. Will you be modifying PACE to read the machine-readable (eg Hatchet) format? Or do you still want a GPTL-like output that PACE can parse? 

In either case, I'll probably still output a human-readable summary into the Log file. Just need to know how many output files/formats we'll need for PACE and other analyses.

**Comment by sarats** [comment]
I'm definitely planning to get GPTL output to begin with. I will experiment with other formats as a supplementary option and once things look good enough, I will look into upgrading PACE etc. to ingest the new format too. But all of this depends on the cost benefit analysis (my big TODO) of these new formats. Meanwhile, I'm planning to get a student to write a converter from GPTL to Hatchet over the summer as well.

**Comment by sarats** [comment]
@grnydawn On a related note, I'm not sure what you mean by "machine readable". Is JSON, Python dataframes etc. good enough or are you looking for some binary format?

**Comment by philipwjones** [comment]
I modified a section to include various output formats. It's pretty general so can accommodate whatever format we eventually decide on while requiring at least a human-readable summary in the Log, even if the timing file is readable.

**Comment by grnydawn** [comment]
> @grnydawn On a related note, I'm not sure what you mean by "machine readable". Is JSON, Python dataframes etc. good enough or are you looking for some binary format?

@philipwjones , @sarats , I did not have a particular format in mind. In general, I think it would be beneficial if the format could be easily created in C++ and parsed by Python or JavaScript. In that sense, JSON could be a good candidate if it meets the requirements to be a format for timing data.

**Pull request merged**
