### PR TITLE
Sync Omega develop with E3SM master

### LINKED ISSUE #54: With `nvidia` on `pm-cpu`, can't build yaml-cpp from ekat
When I try to build Omega on Perlmutter with `nvidia`:
```
export METIS_ROOT=/pscratch/sd/x/xylar/spack_pm-cpu_test//dev_polaris_0_3_0_nvidia_mpich/var/spack/environments/dev_polaris_0_3_0_nvidia_mpich/.spack-env/view
export PARMETIS_ROOT=/pscratch/sd/x/xylar/spack_pm-cpu_test//dev_polaris_0_3_0_nvidia_mpich/var/spack/environments/dev_polaris_0_3_0_nvidia_mpich/.spack-env/view
cmake \
    -DOMEGA_BUILD_TYPE=Release \
    -DOMEGA_CIME_COMPILER=nvidia \
    -DOMEGA_CIME_MACHINE=pm-cpu \
    -DOMEGA_METIS_ROOT=${METIS_ROOT} \
    -DOMEGA_PARMETIS_ROOT=${PARMETIS_ROOT} \
    -DOMEGA_BUILD_TEST=ON \
    -S /global/u2/x/xylar/e3sm_work/polaris/add-omega-ctest-util/e3sm_submodules/Omega/components/omega/ \
    -B .

./omega_build.sh
```

```
[  7%] Building CXX object external/ekat/extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o
nvc++-Error-Unknown switch: -Weffc++
make[2]: *** [external/ekat/extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/build.make:76: external/ekat/extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/src/contrib/graphbuilder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1109: external/ekat/extern/yaml-cpp/CMakeFiles/yaml-cpp.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

### PR DESCRIPTION
**Pull request by philipwjones**
Update the Omega repo to the latest E3SM master to pick up needed changes in cime machine files

Checklist
* [x] Documentation:
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected
* [ ] Testing
  * [x] A comment in the PR documents testing used to verify the changes including any tests that are added/modified/impacted.
  * [x] CTest unit tests for new features have been added per the approved design. 
  * [ ] Polaris tests for new features have been added per the approved design (and included in a test suite)
  * [x] Unit tests have passed. Please provide a relevant CDash build entry for verification.
  * [ ] Polaris test suite has passed
  * [ ] Performance related PRs: Please include a relevant PACE experiment link documenting performance before and after.

Fixes #54

### CODE REVIEW

**Comment by philipwjones** [comment]
@grnydawn after this update, omega can't seem to find the pio.h header file, so something must have changed in the way E3SM builds and installs scorpio. I've tried to find the problem but no luck so far. Any ideas welcome.

Once we do get a successful build, you and @xylar should verify it does indeed fix #54

**Comment by grnydawn** [comment]
@philipwjones, the issue is resolved by adding "PIOC_SOURCE_DIR" and "PIOC_BINARY_DIR" to "$E3SM/components/omega/src/CMakeLists.txt" as shown below. I successfully tested this fix on Frontier. I believe this issue has existed for a long time but has not been visible because we have not really used PIO until we added the IO module.

I will create a small PR for this fix soon before we sync with the E3SM master.

```
target_include_directories(
    OmegaLibFlags
    INTERFACE
    ${OMEGA_SOURCE_DIR}/src/base
    ${OMEGA_SOURCE_DIR}/src/infra
    ${OMEGA_SOURCE_DIR}/src/ocn
    ${PIOC_SOURCE_DIR}
    ${PIOC_BINARY_DIR}
    ${Parmetis_INCLUDE_DIRS}
)  
```

**Review by grnydawn — COMMENTED** [review]
Created a PR (https://github.com/E3SM-Project/Omega/pull/97) to fix PIO-related issue.

**Comment by philipwjones** [comment]
Updated to pick up #98 and fix pio issue. Now passes omega unit tests on Chrysalis/Intel

**Comment by philipwjones** [comment]
@amametjanov - for some reason this update to the latest E3SM breaks your reductions on Frontier GPU. The CPU tests all pass on Frontier but several global sums and global max tests fail on the GPU side. Nothing has changed in Omega and the head of the Omega repo still passes on both, so it seems to be a change on the E3SM side that causes this.

**Comment by amametjanov** [comment]
I reproduced the fails with `gnugpu`; builds with  `crayclanggpu` are still okay though. Trying to narrow down how [these cmake updates](https://github.com/E3SM-Project/E3SM/commit/61dc8c0adcaf7f1a50d52949d96943e2a63d5cc5) are causing fails. Please proceed with the merge.

**Review by xylar — APPROVED** [review]
I ran Omega CTests on Perlmutter-CPU with `gnu`, `intel` and `nvidia`.  I can confirm that #54 seems to be resolved.  I saw the errors reported in #99 but I see them with the current `develop` as well so I don't think that should hold up this merge.

I'm seeing failures in almost all CTests on Perlmutter-GPU with `gnugpu` both with this branch and `develop` and with `nvidiagpu` when I use this branch (I can't even compile with `develop` and `nvidiagpu`), e.g.:
```
	  1 - DATA_TYPES_TEST (Failed)
	  4 - LOGGING_TEST (Failed)
	  5 - DECOMP_TEST (Failed)
	  6 - HALO_TEST (Failed)
	  7 - HORZMESH_TEST (Failed)
	  8 - HORZOPERATORS_PLANE_TEST (Failed)
	  9 - HORZOPERATORS_SPHERE_TEST (Failed)
	 10 - IO_TEST (Failed)
	 13 - IOFIELD_TEST (Failed)
	 15 - REDUCTIONS_TEST (Failed)
```
I will try to find out if I'm doing something wrong at today's Omega meeting and make an issue about this if I'm not obviously messing things up.

**Comment by xylar** [comment]
It looks like Perlmutter-GPU was never working (#55, #56) so don't worry about the failing tests above for this purpose.

**Pull request merged**
