### PR TITLE
Add State design document

### PR DESCRIPTION
**Pull request by sbrus89**
This is a design document for a container for the prognostic state variables withing OMEGA.

Checklist
* [x] Documentation:
  * [x] Design document has been generated and added to the docs
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/

### CODE REVIEW

**Review by philipwjones — COMMENTED** [review]
Thanks for starting this @sbrus89  I have several comments/questions that have also come up for me when trying to develop the tracer doc. I'm interested in others' opinions of these too.

First - do we want to separate the layer thickness and velocity since these are two separate solves (continuity vs N-S)? That would also enable using different time stepping or other algorithms and separate the tendencies as well.

Second, we want to avoid copies so it might make sense to have either a pointer swap or have time levels as an array index (leaning toward the latter for tracers but could go either way). If it's the first index, we can still extract contiguous arrays for the individual time levels but it would avoid expensive copies. This change would also allow more flexibility in time integrations schemes - we could support more than two time levels if we wanted.

Regarding initialization...in our current infrastructure, we had planned to have IOStreams manage all I/O so the restart read would read these fields as part of the restart IOStream. That's the easiest way to manage flexible contents in IO streams. So we can remove the read portion of this class/module.

Once we've settled on the big questions above, then I think we need to have more detail on interfaces, etc in this document.

Thanks again for starting this.

**Comment by philipwjones** [comment]
One other thing I forgot to add - I'm having second thoughts about maintaining host copies of arrays. Especially with Kokkos, I think we should keep everything on the device and only transfer to host with local temps as needed (eg for I/O or MPI if the MPI is not gpu-aware). Having both encourages a model where we'll feel the need to synchronize both to keep them available, where I'd rather make the transfer explicit only when needed.

**Comment by sbrus89** [comment]
@philipwjones, thanks for the comments. I had wondered about some of these things while putting this together, so I'm glad you brought them up. I'm happy to put in more detail once we settle on some of these points.

I like the idea of having the first index for time levels because of the flexibility with time stepping schemes, as you mentioned. The only drawback I can think of is that if this class is also used for tendency/provis variables it would be potentially awkward to have the extra index and in that context.

I think it makes the most sense to keep normal velocity and layer thickness together since they are both involved in computing many of the tendency terms and it makes the function call interface cleaner if they are packaged together, in my opinion.

I agree the initial condition read is better handled by the streams framework, but would this class still need a method to register the normal velocity and layer thickness fields with IOStreams?

The local temp paradigm would also have the benefit of removing the repetition from our member variables. If we go this route, it probably makes sense to go ahead and build the host temp<->device array copy into the IO and Halo infrastructure.

**Comment by philipwjones** [comment]
@sbrus89  I don't think the extra time index would need to apply to tendencies or provisional arrays, just the prognostic variables.  And yes, I'm just about done with an IOField class that implements registration of fields that we want available for IO and provides that list of fields to IOStreams, so look for that PR pretty soon. You would basically register the field initially right after defining metadata as part of initialization. If we have a time index/pointer, you would also need to update the data pointer through an attachData interface as part of the time index update so the IOFIeld continues pointing to the correct location (not needed if we decided to stick with copies rather than index/pointer swapping). Also, I agree that it should be easy to handle the copies to host (if needed) within IO and other interfaces since we have host and device arrays defined as different types.

**Review by mark-petersen — APPROVED** [review]
This is a simple design document. Since there has not been further discussion on it, let's merge it and revise later if needed.

**Pull request merged**
