### PR TITLE
fixed bugs in Omega logging

### PR DESCRIPTION
**Pull request by grnydawn**
Resolves https://github.com/E3SM-Project/Omega/issues/135 and improves logging features

- logging unit testing supports Debug build mode
- logging supports Kokkos arrays having the data types of I4, I8, R4, R8, and Real
- fixes a bug supporting unbuffered logging. Renamed cmake option from OMEGA_LOG_UNBUFFERED to OMEGA_LOG_FLUSH
- enhanced the support logging from selective or all MPI ranks

Checklist
* [X] Documentation:
  * [X] Design document has been generated and added to the docs
  * [X] User's Guide has been updated
  * [X] Developer's Guide has been updated
* [X] Testing
  * [X] CTest unit tests for new features have been added per the approved design.

### CODE REVIEW

**Review by xylar — APPROVED** [review]
@grnydawn, thank you for getting to this so quickly.  I was able to successfully run CTests on Chrysalis build in both debug and release modes.

I don't currently have enough fluency with the logging code to assess the correctness of the changes to the code, just that the test failures reported in #135 are fixed.

A small request for future development: If you make 4 fairly separate changes like you made here (in your 4 bullet points above), could you try to make them in 4 separate commits?  That makes reviewing the PR quite a bit easier, because each set of code changes can be reviewed somewhat in isolation.

**Comment by grnydawn** [comment]
> @grnydawn, thank you for getting to this so quickly. I was able to successfully run CTests on Chrysalis build in both debug and release modes.
> 
> I don't currently have enough fluency with the logging code to assess the correctness of the changes to the code, just that the test failures reported in #135 are fixed.
> 
> A small request for future development: If you make 4 fairly separate changes like you made here (in your 4 bullet points above), could you try to make them in 4 separate commits? That makes reviewing the PR quite a bit easier, because each set of code changes can be reviewed somewhat in isolation.

@xylar, thanks for your review. I will try to create a separate commit for each isolated issue. I had created a bunch of small, private commits for this PR, but I thought it would clutter the develop branch to leave all of them.

**Review by philipwjones — APPROVED** [review]
These look good and I like the name change to FLUSH.  Let me know if you want to merge this as is or break it up.

**Comment by xylar** [comment]
I don't think there's any need to break it up.  I was just making a recommendation for the future.

**Pull request merged**
