### PR TITLE
Add a design document for Tracers

### PR DESCRIPTION
**Pull request by philipwjones**
This is an initial design document for tracer infrastructure. Comments, modifications, alternative approaches are all welcome.

Checklist
* [x] Documentation:
  * [x] Design document has been generated and added to the docs
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected

### CODE REVIEW

**Comment by vanroekel** [comment]
pinging @maltrud and @katsmith133 for input relative to BGC tracers.

@philipwjones one question I recall from BGC folks is the lack of capability to output just select members of a tracer group.  If you wanted a member of a tracer group you'd get the whole group.  Are we able to fix that in OMEGA?

**Comment by philipwjones** [comment]
@vanroekel  Yes, @maltrud had mentioned this to me earlier and 4.1.2 addresses that. If you want a subset of the group members, you can specify them individually and omit the group name from the configuration file. They will still appear as members of the group internally.

**Comment by vanroekel** [comment]
Thanks @philipwjones! I read the document too fast and missed that.

**Review by sbrus89 — COMMENTED** [review]
@philipwjones, this looks like a really nice design. One question I had is about how we plan to handle different source/sink terms for specific tracers/tracer groups.

**Comment by philipwjones** [comment]
@sbrus89  The source/sink terms, like the advection/mixing algorithms, will be mostly managed by the modules that own them (eg the BGC, ecosystem routines, debug/diagnostic tracers). For T,S, they may be sitting in forcing modules or specific modules associated with frazil or other terms. There may need to be tendency driver routine(s), but I'm not certain whether that should sit here or in the time integration routines. There will be too many tracer and algorithmic combinations to manage in a single monolithic tracer module, so this is really just a container to manage the storage and grouping of tracers.

**Comment by sbrus89** [comment]
Thanks @philipwjones , that sounds good to me.

**Review by sbrus89 — APPROVED** [review]

**Review by mark-petersen — APPROVED** [review]
Thanks @philipwjones. I read the design document carefully, and it covers the topics I thought of, which are tracer groups and a time index for arbitrary number of steps in memory. I read through the methods section and appreciate your work here, and I have no comments.

**Pull request merged**
