### PR TITLE
allow only one calendar instance for a simulation

### PR DESCRIPTION
**Pull request by philipwjones**
- converts the calendar class to a singleton class
  - simplifies time instant interfaces (no longer requires a calendar ptr)
  - eliminates requirement to carry/pass a calendar instance everywhere
  - updates documentation and unit tests to reflect new interfaces and functions

Checklist
* [x] Documentation:
  * [x] Developer's Guide has been updated
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected
* [x] Testing
  * [x] A comment in the PR documents testing used to verify the changes including any tests that are added/modified/impacted.
  * [x] CTest unit tests for new features have been added per the approved design. 
  * [x] Unit tests have passed. Please provide a relevant CDash build entry for verification.

### CODE REVIEW

**Comment by philipwjones** [comment]
Fixed bad rebase and bad function definition that intel didn't catch.  Now passes ctest on Chrysalis/intel and Frontier crayclang/crayclanggpu

**Comment by brian-oneill** [comment]
Went through the changes and everything looks good to me. Unit tests pass on Chrysalis and Perlmutter CPU & GPU.

**Review by brian-oneill — APPROVED** [review]

**Review by grnydawn — APPROVED** [review]
Looks good to me. The unit test passed on Frontier with crayclanggpu and amdclanggpu.

Since this time manager is a singleton, I assume it generally will not work in a multi-threaded execution environment. I also notice that we are primarily writing Omega code without considering multi-threading. Therefore, it may be necessary to publicly state that Omega will not generally support multi-threading, although locally isolated multi-threading may still be possible.

**Comment by philipwjones** [comment]
@grnydawn Yes, these functions (and much of the TimeMgr functionality) should occur outside a threaded environment. And I guess the model I have in mind was that threading would happen at the Kokkos kernel level

**Pull request merged**
