### PR TITLE
Added design document for global reductions/collectives

### PR DESCRIPTION
**Pull request by philipwjones**
The design describes reproducible global sums and global min/max
  functionality.

### CODE REVIEW

**Comment by sarats** [comment]
Should we consider an option to use the `shr_reprosum` version (pass-through mode)? This doesn't preclude a C++ implementation, rather as a backup/check.

Evidently, SCREAM folks are using the same, haven't ported it to C++.

**Comment by sarats** [comment]
Wondering if/how we need to account for reproducibility in MPI+OpenMP scenarios. Should we add that as a testing scenario as well?

**Comment by philipwjones** [comment]
@sarats the shr_reprosum requires a contiguous array. For many of our use cases (eg both the restricted index range and the sum-with-mult), we would need to insert a copy and add to the expense. So eventually we need to make that interface a little more flexible in addition to converting to C++ and supporting both YAKL and Kokkos array types, etc. The DDPDD will work in the short term and is easy to implement then we can follow up with a re-written shared reprosum later. I really like what Pat has done, just need to add some features for our use cases.

I will add a requirement and related text on threading. I should also make the host/device aspects more explicit - right now it's buried in the implementation details.

**Comment by philipwjones** [comment]
Until recently, MPAS did not have reproducible sums because they were only used in anaysis where it didn't matter much. When Hyun added the implicit barotropic solver, we added some reproducible sums with DDPDD for similar reasons - it was used for dot products where the sum-with-multiply is really effective and it needed to be performed only over owned cells.

**Review by sarats — APPROVED** [review]

**Pull request merged**
