### PR TITLE
Disable most linting until we have CMake build

### PR DESCRIPTION
**Pull request by xylar**
This merge also adds a clang-format config file.

### CODE REVIEW

**Comment by xylar** [comment]
@philipwjones, if it's easy, could you see if the linter is happier in #19 if you cherry-pick these changes?

**Comment by philipwjones** [comment]
@xylar clang-format works great now, both as a standalone tool and as part of the pre-commit hook

The others (clang-tidy, cppcheck, include-what-you-use) still fail. I haven't tried running those as standalone tools yet, but will check those tomorrow.

**Comment by xylar** [comment]
@philipwjones, I think those are failing because of not having CMake yet, so I disabled them for now.

**Review by philipwjones — APPROVED** [review]
After cherry-picking and testing the pre-commit on #19 this worked fine. I'll go ahead and merge. Thanks @xylar

**Pull request merged**
