### PR TITLE
Rename build workflows

### PR DESCRIPTION
**Pull request by altheaden**
This PR just updates the names of the build and docs workflow files to have `omega-` prepended. This is to keep them from conflicting with the workflow files on the E3SM repo.

This change was supposed to be included in #114 but it was missed - sorry!

### CODE REVIEW

**Comment by xylar** [comment]
@altheaden, can we rename them to `omega-build-workflow.yml` and `omega-docs-workflow.yml`?  I'd prefer to keep them all hyphens, rather than mixed hyphens and underscores.

**Comment by altheaden** [comment]
Oh, sure, me too, I just wasn't sure what the convention needed to be for the functionality to work. I will do that!

**Comment by altheaden** [comment]
@xylar should be done now.

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
@altheaden, yes, looks good to me!

@philipwjones, this is now ready to merge when you have a chance.

**Pull request merged**
