### PR TITLE
Pacer integration into Omega standalone driver

### PR DESCRIPTION
**Pull request by sarats**
This PR adds Pacer timing API and top-level timers to the standalone Omega driver. It includes CMake logic to build and link with Pacer and GPTL.

This PR depends on upstream E3SM PR: https://github.com/E3SM-Project/E3SM/pull/6772
So, we need to sync the Omega repo with upstream once the above PR is merged into E3SM. Then this PR brings in the timing functionality to Omega.

Checklist
* [X] Documentation and Testing: Additional details and testing with standalone driver on Frontier is at https://acme-climate.atlassian.net/wiki/spaces/OO/pages/4775346241/Pacer+timing+interface

### CODE REVIEW

**Comment by sarats** [comment]
> trim trailing whitespace.................................................Failed

AFAIK, I checked the standalone driver and haven't added any trailing whitespace. So, not sure why the pre-commit hook is complaining.

**Review by philipwjones — APPROVED** [review]
Can we also add the timer calls to the standalone test driver in omega/test/driver?  That allows us to check this functionality as part of regular Ctest unit testing. After doing that, I was able to verify that I got timer output that looked reasonable. I'll go ahead and approve since it all builds and works fine otherwise. Tested on both Chrysalis/Intel and Frontier crayclang cpu/gpu.

**Comment by philipwjones** [comment]
btw, the linter is complaining about the trailing space in the two pacer lines in the external/CmakeLists.txt  and it wants the pacer include statement in the driver to sit above the mpi include. Should pass the CI tests after those changes.

**Comment by sarats** [comment]
I trimmed the tab chars added in Youngsung's commit to CMakelists.txt. Anyway, didn't think we were linting CMake files. 

I don't understand the rationale regarding switching the order of including headers (mpi.h, Pacer.h). But did it to satisfy the linter.

**Comment by sarats** [comment]
Forgot to mention, I added the timers to standalone driver test.
@grnydawn Please check if the driver test requires any CMake logic to properly link to Pacer and GPTL.

**Comment by xylar** [comment]
> I don't understand the rationale regarding switching the order of including headers (mpi.h, Pacer.h). But did it to satisfy the linter.

Perhaps it alphabetizes capital letters before lowercase?  I got that sense in my searching.

**Comment by grnydawn** [comment]
@philipwjones , Could you sync the Omega development branch with the E3SM master branch? That way, I can use the Pacer source files from the master branch for this PR. Thanks!

**Comment by sarats** [comment]
What's the standard integration workflow for Omega? Is the practice to get developer to rebase before merging?

For this PR with no conflicts, even just "Rebase and merge" button above would work.

**Comment by grnydawn** [comment]
> What's the standard integration workflow for Omega? Is the practice to get developer to rebase before merging?
> 
> For this PR with no conflicts, even just "Rebase and merge" button above would work.

@sarats, I am not sure if Omega has established a standard integration workflow yet. My understanding was that your forked repository (climatemodeling) is not something I could rebase with, which is why I asked you about it. I didn't know there was a "Rebase and merge" button. Thanks for the tip!

**Review by kieran-ringel — COMMENTED** [review]
I used these timers to test halo exchanges, the timers were easy to add and the output provided the necessary information in an easy to understand format.

**Review by kieran-ringel — APPROVED** [review]
I used these timers to test halo exchanges, the timers were easy to add and the output provided the necessary information in an easy to understand format.

**Pull request merged**
