### PR TITLE
adds an IOField capability

### PR DESCRIPTION
**Pull request by philipwjones**
An IOField capability was part of the IO design and necessary to make fields available for IOStreams. This PR
  - adds a capability to register available fields for IO, including attaching and retrieving metadata and data arrays
  - adds a unit test for this capability
  - adds user and developer documentation

Tested on Chrysalis/Intel. Results of testing across other architectures will be added as they are completed.

Checklist
* [x] Documentation:
  * [x] Design document has been generated and added to the docs
  * [x] User's Guide has been updated
  * [x] Developer's Guide has been updated
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected
* [x] Testing
  * [x] A comment in the PR documents testing used to verify the changes including any tests that are added/modified/impacted.
  * [x] CTest unit tests for new features have been added per the approved design. 
  * [x] Unit tests have passed. Please provide a relevant CDash build entry for verification.

### CODE REVIEW

**Comment by philipwjones** [comment]
Unit test failing on Frontier - debugging...

**Comment by philipwjones** [comment]
Fixed a bad loop index in the test routine. Unit test now passes on Frontier

**Comment by mark-petersen** [comment]
Passes all tests on chrysalis, perlmutter, and frontier


<details>
<summary> notes: </summary> <p>

```

######### Frontier
cd /ccs/home/mpetersen/repos/omega/pr
git submodule update --init --recursive externals/YAKL externals/ekat externals/scorpio cime
cd /lustre/orion/cli115/scratch/mpetersen/runs/240205_omega
module load cmake
rm -rf build
mkdir build
cd build
export PARMETIS_ROOT=$PROJWORK/cli115/pwjones/frontierlibs-cray/parmetis
cmake \
   -DOMEGA_CIME_COMPILER=crayclang \
   -DOMEGA_CIME_MACHINE=frontier \
   -DOMEGA_PARMETIS_ROOT=${PARMETIS_ROOT}\
   -DOMEGA_BUILD_TEST=ON \
   -Wno-dev \
   -S /ccs/home/mpetersen/repos/omega/pr/components/omega -B .
./omega_build.sh
ln -isf /ccs/home/mpetersen/meshes/ocean.QU.240km.151209.nc test/OmegaMesh.nc

salloc -A cli115 -J inter -t 2:00:00 -q debug -N 1 -S 0
cd /lustre/orion/cli115/scratch/mpetersen/runs/240205_omega
./omega_ctest.sh

######### perlmutter
git submodule update --init --recursive externals/YAKL externals/ekat externals/scorpio cime
cd components/omega/
module load cmake
cd /pscratch/sd/m/mpeterse/runs/240205_omega
rm -rf build
mkdir build
cd build
export PARMETIS_ROOT=/global/cfs/cdirs/e3sm/software/polaris/pm-cpu/spack/dev_polaris_0_3_0_gnu_mpich/var/spack/environments/dev_polaris_0_3_0_gnu_mpich/.spack-env/view
cmake \
   -DOMEGA_CIME_COMPILER=gnu  \
   -DOMEGA_CIME_MACHINE=pm-cpu \
   -DOMEGA_PARMETIS_ROOT=${PARMETIS_ROOT}\
   -DOMEGA_BUILD_TEST=ON \
   -Wno-dev \
   -S /global/homes/m/mpeterse/repos/omega/pr/components/omega -B .
ln -s /global/cfs/cdirs/e3sm/inputdata/ocn/mpas-o/oQU240/ocean.QU.240km.151209.nc test/OmegaMesh.nc
./omega_build.sh

salloc --nodes 1 --qos interactive --time 01:00:00 --constraint cpu --account=e3sm
cd /pscratch/sd/m/mpeterse/runs/240205_omega
./omega_ctest.sh

######### chrysalis
git submodule update --init --recursive externals/YAKL externals/ekat externals/scorpio cime
cd components/omega/
module load cmake
rm -rf build
mkdir build
cd build
export PARMETIS_ROOT=/lcrc/group/e3sm/ac.boneill/intel-openmpi-libs
cmake \
   -DOMEGA_CIME_COMPILER=intel \
   -DOMEGA_CIME_MACHINE=chrysalis \
   -DOMEGA_PARMETIS_ROOT=${PARMETIS_ROOT}\
   -DOMEGA_BUILD_TEST=ON \
   -Wno-dev \
   -S .. -B .
ln -isf /home/ac.mpetersen/inputdata/ocn/mpas-o/oQU240/ocean.QU.240km.151209.nc test/OmegaMesh.nc
./omega_build.sh

srun -p debug -N 1 -t 1:00:00 --pty bash
./omega_ctest.sh

```
</details>

**Review by sbrus89 — COMMENTED** [review]
@philipwjones, this capability looks great. The code/docs/testing is all very clean. The only comment I have is to maybe mention in the docs that the host transfer for device arrays will be handled by `IO`, just so it's clear that `IOField` registration isn't limited to host arrays. 

Feel free to disregard if you think this isn't necessary to mention or is better mentioned elsewhere.

**Review by sbrus89 — APPROVED** [review]
Approving based on inspection and @mark-petersen's testing.

**Review by mark-petersen — APPROVED** [review]
Thanks! I read carefully through the documentation and corrected a typo (with the on-line github editor!). Also tested with ctest. Looks good!

**Comment by philipwjones** [comment]
Thanks @mark-petersen and @sbrus89  I added a sentence to the devGuide in response to Steven's comment.

**Comment by xylar** [comment]
@philipwjones, this introduced some links in the docs:
```
[IOStreams](#omega-dev-iostreams)
```
and
```
[IOStreams](#omega-user-iostreams)
```
that don't seem to exist.  Is this something that will be added later or is it something that got renamed?

**Pull request merged**
