### PR TITLE
Some updates to the documentation

### PR DESCRIPTION
**Pull request by xylar**
This merge adds documentation on updating conda environment.  It also does a little rearranging of the pages in the developer guide to (hopefully) be a little more intuitive.  We obviously have a long way to go...

Checklist
* [x] Documentation:
  * [x] Developer's Guide has been updated
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected

### CODE REVIEW

**Comment by xylar** [comment]
I'm seeing:
```
/home/xylar/code/e3sm/Omega/omega/fix-docs/components/omega/doc/devGuide/IO.md:5: WARNING: 'myst' cross-reference target not found: 'omega-user-iostreams' [myst.xref_missing]
/home/xylar/code/e3sm/Omega/omega/fix-docs/components/omega/doc/devGuide/IOField.md:13: WARNING: 'myst' cross-reference target not found: 'omega-dev-iostreams' [myst.xref_missing]
/home/xylar/code/e3sm/Omega/omega/fix-docs/components/omega/doc/userGuide/IO.md:5: WARNING: 'myst' cross-reference target not found: 'omega-user-iostreams' [myst.xref_missing]
/home/xylar/code/e3sm/Omega/omega/fix-docs/components/omega/doc/userGuide/IOField.md:5: WARNING: 'myst' cross-reference target not found: 'omega-user-iostreams' [myst.xref_missing]
```
when I build the docs locally.  This seems to be from #66.  @philipwjones, let me know if you'd like me to do anything about that here or if a future PR will add the missing documentation.

**Comment by xylar** [comment]
@grnydawn, can you take a look at the docs I added and see if they work for the situation you brought up today?  I think they should.

**Review by grnydawn — APPROVED** [review]
I followed the directions outlined in CondaEnv.md to renew my conda environment, and it worked well.

**Review by philipwjones — APPROVED** [review]
Looks fine and the re-ordering is good so far.

**Pull request merged**
