### PR TITLE
Adds memory cleanup functions for some Omega classes

### PR DESCRIPTION
**Pull request by philipwjones**
For Omega classes that store all instances, this adds some erase/clear functions to clean up memory before the yakl finalize call. Updates developer guide to note the requirement for this cleanup.

This fixes a bug in the initial Decomp implementation that was preventing the successful use of device arrays so the Decomp device arrays are now enabled with this PR.

All tests pass on Chrysalis/Intel. Will test on others and update.

Checklist
* [x] Documentation:
  * [x] Design document has been generated and added to the docs
  * [x] User's Guide has been updated
  * [x] Developer's Guide has been updated
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected
* [x] Testing
  * [x] A comment in the PR documents testing used to verify the changes including any tests that are added/modified/impacted.
  * [x] CTest unit tests for new features have been added per the approved design. 
  * [x] Unit tests have passed. Please provide a relevant CDash build entry for verification.

### CODE REVIEW

**Comment by philipwjones** [comment]
@grnydawn thanks for catching that - I had fixed some of those in other PRs but looks like I missed this one, just pushed the change

**Review by brian-oneill — APPROVED** [review]
Built and tested on Frontier and Chrysalis, no issues. Will keep these requirements in mind going forward.

**Comment by xylar** [comment]
@brian-oneill, it looks like you did squash-merges when you merged this and #43.  Unless I'm mistaken, I think we instead want merge commits and to preserve the commit history.  @philipwjones, correct me if that's not correct.

**Comment by philipwjones** [comment]
@xylar I have been doing squash merges of some of these, especially if many of the commits are minor tweaks like formatting in response to linting. So it's been a little bit of a judgement call in keeping any significant history while not introducing too much clutter.  I don't know that we ever established a formal rule on this so let me know if you prefer otherwise and we can all decide.

**Comment by xylar** [comment]
Oh, okay, that's fine. Just wanted to check since that hasn't been the E3SM practice.

**Comment by rljacob** [comment]
Feature branches should always be added to master with a merge commit.   Within a feature branch, you can squash commits to clean up its history.

**Comment by xylar** [comment]
@rljacob, does the `develop` branch here count as a very complex "feature" branch?  Or as the equivalent of `master`?

**Comment by rljacob** [comment]
"develop" would be like a really long-lived feature branch.

**Comment by xylar** [comment]
Thanks @philipwjones and @rljacob for the clarification.  The squashing approach seems fine to me in that case.  I can see that the benefits for future debugging probably outweigh the potential costs -- it's a huge pain to wade through a bunch of needless fixup commits.

**Pull request merged**
