### PR TITLE
Add mesh operators

### PR DESCRIPTION
**Pull request by mwarusz**
This PR adds a couple mesh operators: gradient, divergence, curl, and tangential velocity reconstruction. A test comparing the result of applying the numerical operators to an analytical solution on a planar hexagonal mesh is added.

Additionally, this PR uses CMake to automatically download the meshes needed for running the tests. It also fixes a couple of bugs in the horizontal mesh class and tests, that showed up only when running on a gpu.

This is a work in progress, but early feedback is welcome.

Checklist
* [x] Documentation:
  * [x] User's Guide has been updated
  * [x] Developer's Guide has been updated
  * [x] Documentation has been [built locally](https://e3sm-project.github.io/Omega/develop/devGuide/BuildDocs.html) and changes look as expected
* [x] Testing
  * [x] CTest unit tests for new features have been added per the approved design. 
  * [x] Unit tests have passed. Please provide a relevant CDash build entry for verification.

### CODE REVIEW

**Comment by mwarusz** [comment]
This PR is now ready for review. I have updated it to:
- remove CMake handling of mesh files, since it is a separate issue that needs further discussion
- add a test for horizontal operators in spherical geometry
- add documentation

The new spherical test initial conditions are taken from https://doi.org/10.1016/j.ocemod.2024.102335.

Unit tests pass on CPUs on Chrysalis, Perlmutter, Frontier, and on the GPU on Frontier. Running the tests is very awkward with this PR, since three different meshes need to be used. I can add instructions on how to do this to the docs, but I would rather figure out a way of making this process easier. Here are the instructions:

```
# get the meshes
wget -O ocean_test_mesh.nc https://web.lcrc.anl.gov/public/e3sm/inputdata/ocn/mpas-o/oQU240/ocean.QU.240km.151209.nc
wget -O planar_test_mesh.nc https://gist.github.com/mwarusz/f8caf260398dbe140d2102ec46a41268/raw/e3c29afbadc835797604369114321d93fd69886d/PlanarPeriodic48x48.nc
wget -O global_test_mesh.nc https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/polaris_cache/global_convergence/icos/cosine_bell/Icos480/init/initial_state.230220.nc
# on a compute node after building Omega do
source omega_env.sh
ln -sf  ocean_test_mesh.nc test/OmegaMesh.nc
ctest -E HORZOPERATORS
ln -sf  planar_test_mesh.nc test/OmegaMesh.nc
ctest -R HORZOPERATORS_PLANE
ln -sf  global_test_mesh.nc test/OmegaMesh.nc
ctest -R HORZOPERATORS_SPHERE
```
CI failure will be fixed by #65.

**Comment by mwarusz** [comment]
In order to be fast, the operators unit tests only check error values on a single coarse mesh. However, I also performed convergence tests on a sequence of increasingly finer meshes. For reference, here are the results:

Planar meshes:
[conv_planar.pdf](https://github.com/E3SM-Project/Omega/files/14426540/conv_planar.pdf)

Icosahedral global meshes:
[conv_icos.pdf](https://github.com/E3SM-Project/Omega/files/14426545/conv_icos.pdf)

Here, the convergence rates for some operators are worse than those reported in https://doi.org/10.1016/j.ocemod.2024.102335. I guess they had better meshes ?

**Comment by xylar** [comment]
@mwarusz, my understanding is that the icosahedral meshes are as good as is possible on a sphere.  I think we should double check that the operators are behaving as they should on pentagons.  If so, maybe the poor L-infinity performance can't be helped.  But I would think it wouldn't be quite so bad.

**Comment by xylar** [comment]
@mwarusz, are you actually using the icosahedral meshes or are you using quasi-uniform meshes in the more rigorous convergence test?  Where are you getting the meshes from or how are you generating them?

**Comment by mwarusz** [comment]
@xylar  I am using the icosahedral meshes from here: https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/polaris_cache/global_convergence/icos/cosine_bell/. I also have results on quasi-uniform meshes , but they look much worse:

[conv_qu.pdf](https://github.com/E3SM-Project/Omega/files/14437499/conv_qu.pdf)

**Comment by xylar** [comment]
Okay, thanks.  I'll be quiet now since I think others on the team will be able to contribute better to this conversation than I can.  I appreciate the hard work and careful testing!

**Review by philipwjones — COMMENTED** [review]
Thanks @mwarusz for these. Some of the comments below just reflect the fact that this is the first actual implementation of stuff so have hit things we haven't discussed much as a group yet. But I think the biggest concern is the lack of convergence so we may need to look into that more unless @mark-petersen says they work the same way in MPAS.  Other comments:

We haven't talked about this, but how do we feel generally about implementing some simple functions like these in the header files rather than the traditional header (interfaces)/ cpp (implementation) split. I'm probably ok either way as long as they're simple, but don't know how rigid people want to be.

On documentation: the user doc is fine - might just add one sentence that says there are no user-configurable options. For the devGuide, I would like us to treat it like a reference manual so that we can trace the math through the discretization to the actual implementation with variable names. We haven't needed to do this for the infrastructure (except we do need to go back and reproduce the mesh figure for the HorzMesh), but as we actually start implementing math/tendencies, we should get in the habit of providing this level of detail. Mark might have some of the original LaTeX from the MPAS papers.  That detail would be useful for these code reviews too so we can verify code against the doc.

On testing: IMO, I think for the unit test in CTest, a single test against on analytic field on a coarse mesh is probably fine with some bound on Linf norm (and maybe L2 norm too?). We can do the convergence testing in Polaris where we expect to do other convergence tests.

I will hold off on approval until we have the detail in the devGuide and have more info on the convergence issues.

**Review by sbrus89 — COMMENTED** [review]
@mwarusz, I tested this successfully on Frontier and think your implementation is nice. 

My only comment is that perhaps we should take this opportunity to streamline/clarify the tests that require different mesh configurations. I think it makes sense to require that all ctests use one of three standard meshes: 1) ocean-culled QU (OmegaOceanMesh.nc), 2) planar (OmegaPlanarMesh.nc), 3) full-sphere icos (OmegaSphereMesh.nc).  Each test can then use the appropriate mesh instead of just the default. This would allow us to run all the ctests at once instead of switching links to OmegaMesh.nc. I think any other tests that require mesh configurations outside of these three can be handled in polaris testing.

I'm also puzzled about the sphere convergence, but I think we can merge and make an issue as we continue to investigate. I'm optimistic that using the SVT optimized meshes will help somewhat.

**Comment by mwarusz** [comment]
As part of updating this PR I streamlined the use of different mesh configurations. To setup the meshes do
```
wget -O ocean_test_mesh.nc https://web.lcrc.anl.gov/public/e3sm/inputdata/ocn/mpas-o/oQU240/ocean.QU.240km.151209.nc
ln -sf  ocean_test_mesh.nc test/OmegaMesh.nc
wget -O planar_test_mesh.nc https://gist.github.com/mwarusz/f8caf260398dbe140d2102ec46a41268/raw/e3c29afbadc835797604369114321d93fd69886d/PlanarPeriodic48x48.nc
ln -sf  ocean_test_mesh.nc test/OmegaPlanarMesh.nc
wget -O global_test_mesh.nc https://web.lcrc.anl.gov/public/e3sm/polaris/ocean/polaris_cache/global_convergence/icos/cosine_bell/Icos480/init/initial_state.230220.nc
ln -sf  ocean_test_mesh.nc test/OmegaSphereMesh.nc
```
and then run `omega_ctest.sh` as usual.

 @mark-petersen

**Comment by mark-petersen** [comment]
Thanks! I was able to successfully run all 15 tests on Frontier with those files.

**Comment by mark-petersen** [comment]
I think this PR can serve as a way to discuss and iterate on our design of how the operators use Kokkos. @brian-oneill please test and review, particularly the use of your halo exchange code.

**Review by mark-petersen — APPROVED** [review]
I have looked through this code, and I like @mwarusz's approach of wrapping all the tendency calls within a single Kokkos lambda, and then having functors for each tendency term in another file. 

I'm at the E3SM tutorial next week, then mostly out in May on another trip and vacation. I know there will be further discussion of the details here, but I'm approving so I don't hold up the process while I'm out.

**Comment by sbrus89** [comment]
Approved based on successful testing on Frontier (CPU and GPU). Thank you @mwarusz for tracking down the source of the unexpected convergence issues!

**Review by sbrus89 — APPROVED** [review]

**Review by philipwjones — APPROVED** [review]
@mwarusz This looks fine and I have replicated testing on Chrysalis and Frontier. I'm going to approve, but request one last change. Could you please add instructions for setting up the three input files to the userGuide/OmegaBuild.md file in the paragraph where the ctest script is described?  Thanks.

**Comment by mwarusz** [comment]
>  I'm going to approve, but request one last change. Could you please add instructions for setting up the three input files to the userGuide/OmegaBuild.md file in the paragraph where the ctest script is described?

@philipwjones 

I have updated the docs to include information on getting the three meshes, but I put it in a different place than you suggested. I put it in `devGuide/QuickStart.md`, since there already was some (outdated) information there. I added a link to this paragraph in `userGuide/OmegaBuild.md`. Let me know if you want me to handle this differently.

**Comment by philipwjones** [comment]
Thanks @mwarusz - that does look like a better place in the docs.

**Pull request merged**
