### PR TITLE
Update pre-commit dependencies

### PR DESCRIPTION
**Pull request by xylar**
This merge also adds pre-commit ci, which will (hopefully) make a PR to update these dependencies on a monthly basis.

Checklist

### CODE REVIEW

**Comment by xylar** [comment]
I noticed that local linting and CI produced different results from each other in #138.  I don't see why this update would change that but I want to rule out old dependencies being the reason.

**Comment by xylar** [comment]
@altheaden, can you have a look at this one, too?

**Comment by altheaden** [comment]
@xylar this looks good to me, of course we'll have to wait to see if the auto-update works as expected (I assume).

**Comment by xylar** [comment]
> we'll have to wait to see if the auto-update works as expected (I assume).

Yes, I'm afraid I don't really understand how it's supposed to work and there isn't much info I could find online.

**Pull request merged**
