### PR TITLE
Move Tendencies class into separate files

### PR DESCRIPTION
**Pull request by mwarusz**
This is a small PR that separates the `Tendencies` class from the tendency terms files into its own set of files. This was suggested in  https://github.com/E3SM-Project/Omega/pull/109#issuecomment-2294102662, but we never got around to it. Since there are no open conflicting PRs, now it is a good time to do it.
 
* [x] Testing
  * [x] Unit tests have passed. Please provide a relevant CDash build entry for verification.

### CODE REVIEW

**Comment by mwarusz** [comment]
CTests pass on Chrysalis and Frontier.

**Comment by hyungyukang** [comment]
I tested this branch using the manufactured solution, which requires modifications to the `Tendencies.cpp` file in this PR.

I was able to run the manufactured solution test with the changes incorporated in this pull request.

**Review by sbrus89 — COMMENTED** [review]
I think there are include statements in `OceanFinal.cpp` and `OceanInit.cpp` that should be changed from `TendencyTerms.h` to `Tendencies.h` as well.

**Comment by mwarusz** [comment]
> I think there are include statements in OceanFinal.cpp and OceanInit.cpp that should be changed from TendencyTerms.h to Tendencies.h as well.

@sbrus89  Done.

**Review by sbrus89 — APPROVED** [review]
Thanks, @mwarusz. This looks good.

**Pull request merged**
