### PR TITLE
added initial directory structure and template design doc

### PR DESCRIPTION
**Pull request by philipwjones**
Third time's a charm?  This is the same initial directory structure and Markdown(MyST) design template from the similar PRs to the other attempts at an OMEGA repo.

### CODE REVIEW

**Review by sarats — APPROVED** [review]
Same as before.

**Comment by xylar** [comment]
@philipwjones and @sarats, the target here should be `develop`, not `master`.

**Comment by xylar** [comment]
I changed it, I hope you don't mind.

**Review by xylar — CHANGES_REQUESTED** [review]
I think we would prefer at this point to use MyST (i.e. markdown) format rather than RST for the READMEs.  I'm happy to make the changes but I think it amounts to renaming the files (`README.md`) and changing titles to be in this format:
```
# The Ocean Model for E3SM Global Applications (OMEGA)
```

**Comment by sarats** [comment]
Don't really have a horse in this race but did we decide on MyST vs. RST? I thought you were okay with RST but not with hosting at ReadtheDocs.

**Comment by sarats** [comment]
In a general sense, let's get this PR done for the basic directory structure. Perhaps we can get the documentation format changes afterwards?

**Comment by xylar** [comment]
@sarats, I'm fine either way but I think changing the format is a maybe 20 minute job.  It seems easier to do now that later.

I felt like I was the only one pushing for RST format in the past.  The main reason for that was that there was not consistent support for markdown in the past, and limited support for things like equations.  That seems to have changed with MyST.  Since markdown is what we all use on GitHub already, it seems like a no-brainer to go with markdown for documentation as well.  I don't see any strong argument to stick with RST at this point.

I'm willing to hear any counterarguments folks may have but I am also willing to assert my authority as the lead of the documentation team to say that we're going with MyST unless someone convinces me otherwise.

**Comment by xylar** [comment]
A can also say that I have successfully converted the documentation for polaris from RST to MyST here:
https://github.com/E3SM-Project/polaris/tree/main/docs
The process was relatively painless (using the [rst-to-myst](https://rst-to-myst.readthedocs.io/en/latest/)) tool and any complications had to do with sphinx rather than RST or MyST formats themselves.  The result is, in my view, unquestionably better an more intuitive than RST, which I have worked with for a couple of years now.

**Comment by xylar** [comment]
@philipwjones, if you're okay with switching to MyST, you can cherry-pick the final commit on this branch:
https://github.com/xylar/E3SM/tree/omega/init-dirs

**Comment by philipwjones** [comment]
Changed to Markdown format - ended up doing it manually to adjust some formatting in template file.

**Review by xylar — APPROVED** [review]
Sounds good!  Thanks for making th transition.

**Review by mark-petersen — APPROVED** [review]
Checked directories and markdown templates. Looks good. Thanks @philipwjones!

**Comment by philipwjones** [comment]
Would someone like to merge/integrate? Got a lot of design docs and other stuff to start adding, so be good to have this initial setup in place.

**Comment by philipwjones** [comment]
Thanks @sarats

**Pull request merged**
